- hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: firewall rules
    firewalld:
        port: "{{ item }}"
        state: absent
        permanent: true
        immediate: true
    with_items:
        - 161/tcp
        - 162/tcp
