---
- name: Enterprise Production Fleet Drift Remediation
  hosts: all
  sources:
    - ansible.eda.webhook:
  rules:
    - name: Remediate Infrastructure Configuration Drift
      condition: event.payload.alert_name == "ConfigurationDriftDetected"
      action:
        run_job_template:
          name: "Demo - Remediate Drift"
          organization: "Default"
          job_args:
            extra_vars:
              eda_drifted_host: "{{ event.payload.drifted_host }}"
