---
- name: Listen for Disk Alerts via Event Stream
  hosts: all
  sources:
    - ansible.eda.pg_listener: {}  # Use {} instead of leaving it blank
  rules:
    - name: Cleanup /var/log when filesystem > 80%
      condition: 
        # IMPORTANT: Use .alerts[0] because Alertmanager sends a list (array)
        event.payload.alerts[0].status == "firing" and
        event.payload.alerts[0].labels.mountpoint == "/var/log"
      action:
        run_job_template:
          name: "Disk Cleanup Playbook"
          organization: "Default"
          limit: "{{ event.payload.alerts[0].labels.instance.split(':')[0] }}"
          job_args:
            extra_vars:
              #target_host: "{{ event.payload.alerts[0].labels.instance }}"
              target_host: "{{ event.payload.alerts[0].labels.instance.split(':')[0] }}"
